### PR TITLE
Yoda condition fix in url_origin()

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Yoda condition in /docs/functions/get-current-url.php as per https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions document

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@jeffpaul Can you please check this?

**Comment by jeffpaul** [comment]
I thought, at first, that this was a change to some docpress files (in which case I was going to recommend we push the change upstream and then update when docpress releases the change).  However, this code does appear to be custom when we originally built out the docs site back in the summer of 2018.  I'm generally ok with these changes, but not certain what coding standard we're following for the docs site and whether WPCS fully applies here?

**Comment by mukeshpanchal27** [comment]
Respected @jeffpaul,

Do I need to update the pull request? or it is your thought?

**Review by pierlon — APPROVED** [review]
> I'm generally ok with these changes, but not certain what coding standard we're following for the docs site and whether WPCS fully applies here?

Having a coding standard like WPCS in place would be great here, and could be considered an enhancement. For now, these changes are fine.

**Pull request merged**
