### PR TITLE
WIP: Update documentation structure and content

### PR DESCRIPTION
**Pull request by luboskmetko**
I'm creating this new PR because I somehow messed up previous PR and couldn't commit more updates to it.

### CODE REVIEW

**Comment by luboskmetko** [comment]
@jeffpaul here are those additional questions regarding documentation:

- Does project need to be installed into specific folder because of Go? I couldn't build servers, getting errors like this:

```
[INFO]  Replacing existing vendor dependencies
Cleaning up Lighthouse Server GO binary 'bin/lighthouse-server' ...
Building Lighthouse Server GO binary 'bin/lighthouse-server' ...
cmd/lighthouse-server/main.go:10:2: cannot find package "github.com/wptide/pkg/env" in any of:
        /usr/local/Cellar/go/1.10.2/libexec/src/github.com/wptide/pkg/env (from $GOROOT)
         /Users/lubos/go/src/github.com/wptide/pkg/env (from $GOPATH)
  ```

- Will Google Cloud SDK/Google App Engine setup still be required for local development as described here https://github.com/xwp/go-tide/tree/gcp-providers#google-cloud-sdk? If not, I'd move it under GCP chapter.

Thanks

**Comment by luboskmetko** [comment]
Documentation now describes how installing Tide locally works at the moment - I was able to install everything up to the point that I was getting audits in WP admin when running sync server. Although, currently it still requires to:

- clone Tide project to specific project under `GOPATH` (seems it has to be `src/github.com/xwp`)
- install and configure Google Cloud SDK and set GCP project values in the `.env`file

If this changes in the near future, we can update the docs. Tomorrow I would take a look at the API endpoints.

**Comment by valendesigns** [comment]
@luboskmetko I'll be traveling to WCEU and will look at the local install tomorrow. It shouldn't require creating a GCP project anymore but I need to install locally and validate that. We've added local providers for both report storage and an audit queue.

**Comment by luboskmetko** [comment]
@valendesigns thanks. I had to set up GCP because when building server images, eg. `make lighthouse.build.image`, I got an error with a link like `gcr.io/<CHANGE_THIS_VALUE>`. According the Makefile the value was referring to `${GCP_PROJECT}`, and it started to work when I set those up.

**Comment by luboskmetko** [comment]
@valendesigns @jeffpaul I was documenting API endpoints today, the attached image shows how it looks like in docpress for now (we can copy to the theme later). There are a few things unclear to me, mostly on the endpoints which are missing arguments description:

- as Derek mentioned on Slack `/tide/v1/report` requires a bearer token. Is there way how to get this token and test it out? 
- `/tide/v1/auth` - what credentials to use and how to pass them to this endpoint?
- `/tide/v1/keypair/{id}` - not sure what this does
- `/tide/v1/audit_project` - getting `rest_forbidden` on this
- `/tide/v1/audit_project/{id}` - getting something here but unclear what's its purpose

Thanks

api-endpoints-docs

**Comment by luboskmetko** [comment]
Closing this as all content was transferred in the new PR.

**Pull request closed without merging**
