### PR TITLE
migrate GitHub wiki content

### PR DESCRIPTION
**Pull request by jeffpaul**
Resolves items from https://github.com/wptide/wptide/issues/132

### CODE REVIEW

**Comment by jeffpaul** [comment]
Once this PR gets merged, we'll want to delete the following wiki pages:
- [ ] https://github.com/wptide/wptide/wiki/Running-Lighthouse-audits

**Comment by jeffpaul** [comment]
Note that I'm uncertain that creating these index.md files will actually add the corresponding menu link in the left nav, though I searched and was unable to find a way to handle that definitively.  So I'm passing this along as no longer WIP, but ready for review.

**Comment by jeffpaul** [comment]
Resolves https://github.com/wptide/wptide/issues/132

**Comment by jeffpaul** [comment]
Resolves https://github.com/wptide/wptide/issues/79

**Comment by jeffpaul** [comment]
- [ ] integrate update from [README](https://github.com/wptide/wptide/pull/167/files#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by valendesigns** [comment]
I had to fix the docs and merge this in a different branch and back to develop. It's all fixed now and this PR can be closed.

**Pull request closed without merging**
