### PR TITLE
Merge scaffolded WordPress theme work 

### PR DESCRIPTION
**Pull request by postphotos**
Hi @MakiBM, your work here is great! I'm opening this PR to capture the discussion in the repo.

~1) Can you update all single font declarations from `sans-serif` to the full string? (`font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`) or I can do this, too.~
Done

2) I ran into issues with sublinked pages in my local. Is there pages to represent them in WordPress or something? Since we're after contributors here, getting this fixed and/or documented should be a goal for as soon as possible.

~3) I have a few minor copy tweaks I'll file in a small PR to the `README` likely tomorrow.~
Done.

~4) There's, of course, likely some open work that @luboskmetko is still working on, but I would like to see this stood up as soon a swe can.~
Consider Done. Lubos confirmed on the slack channel that theme branch contains all oh his work so after merging this branch to master he can continue there if needed

If we can get 1 + 2 addressed here, we should merge to `master` and deploy formally to our own staging environment and/or the `wptide.org` site. As 3 + 4 and anything else may come up, we should document internally a deploy process (or leverage a CI process to do that whenever we merge to `master`.)

### CODE REVIEW

**Comment by postphotos** [comment]
I added my tweaks here as well as added a line of prose to the search tool to explain how it works. @MakiBM, based on our last conversation we're only using vanilla CSS here, so I committed with that in mind. 

Note: In my tired state, I noticed I may have minified the CSS file in running the build process, so let's fix that before moving forward and document that, too.

**Comment by postphotos** [comment]
@luboskmetko - thanks for your hard work here! :1st_place_medal: :bowing_man: 

@MakiBM - confirming #2 above is related to the `request_uri` implementation we spoke about this morning. I tried standing it up again on a different machine and found the same basic problem:

- Running in `valet` at `https://tidedocs.test` I cannot load any subpages.
- I can build and display all assets just fine.
- This appears to work on your testing server, but not in a multi-host environment.

I think we should break this issue out and continue to work on that so this PR can be merged.

**Comment by valendesigns** [comment]
This should be a PR to `develop` not `master`. Do not merge this into `master`!

**Comment by valendesigns** [comment]
Closing in favor of #15

**Pull request closed without merging**
