### PR TITLE
updated typo in image

### PR DESCRIPTION
**Pull request by jankimoradiya**
Hello,

 I have updated "architecture-diagram.png" image because. there is a typo in "stroreage". 

Issue posted in below link:
https://github.com/wptide/docs/issues/24#issue-424360794

Thanks

### CODE REVIEW

**Comment by jeffpaul** [comment]
@joshuawold I think you created the source image.  Does this update look correct to you?

**Comment by jwold** [comment]
Good catch! @jeffpaul, yes this looks good. Is any action needed on the graphic?

**Comment by jeffpaul** [comment]
@jwold if the image quality looks good to you, then I think we're good

**Comment by jeffpaul** [comment]
As I'm not fully certain how the docs site gets built, I'm not positive that just changing the image here will resolve the issue so I'll await confirmation from @valendesigns on what else might be needed.

**Comment by valendesigns** [comment]
There is another issue in the image which makes in inaccurate. Is there a file I can edit?

**Comment by jankimoradiya** [comment]
Hello @valendesigns,

I have attached file with updated typo in "stroreage" word.

architecture-diagram-updated


Thanks

**Comment by jeffpaul** [comment]
Resolves #24.

**Pull request merged**
